### PR TITLE
Test version 0.3?

### PR DESCRIPTION
**Pull request by Tobbe321**
It seems that you Jeppe has an 0.3 version of the Samsung PlaySE-Smart-TV-app.
Is it possible to try and install from somewhere? 
It would be very interesting to test!
Best Regards,
Torbjörn Nordqvist
email: torbjorn@nordqvist.se

### CODE REVIEW

**Comment by JeppeTh** [comment]
Not sure what you mean...

Kantaris 0.3 is available here (not sure why not in github)
http://188.40.102.5/Widget/

My somewhat modifed version is available in git
https://github.com/JeppeTh/PlaySE-Smart-TV-app/archive/master.zip

However it seems Kanaris hasn't completly updated his server for new SVT Play format

**Comment by Tobbe321** [comment]
That's just  the problem, Kantaris server only holds 0.2.0 version to be installed on the Samsung TV.
Is the 0.3 version available somewhere in an installable format in the same way?
Or how can I install your html-version on my TV?

**Comment by JeppeTh** [comment]
Really - I'm pretty sure you get 0.3 from Kantaris server:

See http://188.40.102.5/widgetlist.xml

I'm guess there's some guide on Internet on how to install it. I installed XAMPP which can run an apache server. Then you jut put the zip file in a Widget folder. And make a widgetlist.xml as above, put in the folder above. But which the IP and so on to your own.

Then you need to change "development ip" on your samsung device before syncing applications.

**Comment by Tobbe321** [comment]
You are right - Kantaris is 0.3 now. I was fooled by their web page still saying 0.2.
Thanks for the info and the 0.3 version works fine even with the new SVT Play format.

**Comment by JeppeTh** [comment]
But it doesn't work fine right? At least not everything.

I.e. choosing a category doesn't work for me at least...
Also if searching for a show - I can't select the show - only the episodes works...

**Comment by Tobbe321** [comment]
You are right - Kantaris 0.3 version fails in a lot of areas. 
But it also works OK in some, like live channels.
I hope Kantaris can find the time to adapt to the latest SvtPlay format. There are a lot of us with Samsung TV´s that would be most greatful not having to connect a PC or using other equipment like EZcast+Android app.

**Comment by Pertan** [comment]
Anyone else still experiencing problems with 2012 TV set? After kantaris took down his server I tried installing several of the versions from here with no success. Only blank screens, maby SVT changed something again?

**Comment by JeppeTh** [comment]
The app is dependant on his server, without it nothing works. It's possible to change app so it works directly towards SVT, but perhaps it gets too slow then.

**Comment by Pertan** [comment]
Jeppe, noticed that dependancy when I browsed the code. It would be nice if Kantaris could share this code with us (so we can Run it on a local webbserver instead). Looks like Kantaris has stopped the development, so maby he can share it now?

**Comment by JeppeTh** [comment]
@Pertan, I made a version which works towards SVT. I guess this ones cosumes more memoy - but I believe it works pretty ok anyhow. You can find it in my repo.

EDIT:
Hadn't tested it on actual device especially much, only on simulated. Realized my version doesn't work so well on my old devices at least... Perhaps a memory issue...

**Comment by Pertan** [comment]
@JeppeTh  Your version did not work at the 2012 simulator, but i installed it at my d8005, alas! Works like a charm! Thx a lot! Finaly able to watch SVT Play. Wonder why SVT wont support this! Will report back if i find issues. Thx again!

**Comment by JeppeTh** [comment]
@Pertan, ok nice to hear. I'll run it on 2012 simulator and try it out. 
On my blurays (one d and one c) I have issues with mem (run out of stack quota). But these have limited amount of mem I believe. For instance I can't list channels and live shows,  nor categories with lot of shows. E.g 'Barn'.

Do you hsve a 2012 device as well, did you try it on that? I.e does it fail only in simulator or also on actual device?

**Comment by Pertan** [comment]
@JeppeTh using samsungs 2012 emulator gives me black screens when trying to stream anything. But at my UE55ES8005 (tested with firm 002009 & 002015) everything works. Browsing categories with many items (eg. "Barn") & live shows. At first i thought Live did not work, got "Network error", but it might have due to no live stream. Anyway, it works if i pick the "correct" live Channel. 

stocastic Im getting Network error, but just reload and it works again

The build in browser still buffers every 10 seconds. I do not use wifi, i connect thru Ethernet cabel.

Thx again

**Comment by Tobbe321** [comment]
Hi all,
Maybe a stupid question... but how can I download Jeppes new version to my TV? I guess I first have to download the files to my PC, but how do I go from there? I know how to use develop/develop and set the IP of my server. But how do I organize the files on my PC to make the sync?
Tnaks for helping out.

**Comment by Pertan** [comment]
Quick guide:
1) build a package with Samsung TV SDK (or use one downloaded from git as Jeppe says)
2) copy zip to \widget at webbserver 
3) Edit widgetlist.xml
4) sync in smart tv

Use unique name, if u want to preserve original app.
Maby there are easier ways to do it, but this works

**Comment by JeppeTh** [comment]
Not sure you need to build one,  can't zip from git be used?

Here's a guide:
https://wiki.samygo.tv/index.php?title=How_to_install_custom_widgets_to_TV

**Comment by Tobbe321** [comment]
If so, I guess I have to create the widgetlist.xml myself?

**Comment by Pertan** [comment]
Well, yes, follow instructions at 
http://wiki.samygo.tv/index.php5/How_to_install_custom_widgets_to_TV
Very strait forward..

**Comment by Tobbe321** [comment]
Tried that, both easy way and long way. And the TV finds the app and says it will be installed but it is not. The istall count in the finishing message is blank.
My TV is D8005.
Any hints?

**Comment by JeppeTh** [comment]
What does your widgetlist.xml look like?

**Comment by Tobbe321** [comment]
It looks like this:

image

**Comment by JeppeTh** [comment]
Have you placed the zip file in a widget folder placed in same folder as widgetlist.xml?

Have you checked that you download url above works - i.e .in a browser?

You could try to link to git directly
https://github.com/JeppeTh/PlaySE-Smart-TV-app/archive/master.zip

**Comment by Tobbe321** [comment]
Yes on all three suggestions.
I even put an idex.html just to check and it was displayed from another computer.
It still says "slufört" (Finished), with blank in count. Nothing is installed.
Could it be the size? I calculated  374 kB x 1024 = 382976.
It now looks like this:
image

**Comment by JeppeTh** [comment]
"it was displayed" - are you talking about widgetlist.xml or the download url (now meaning github-url...)?

If it doesn't work - perhaps the zip files isn't possible to use - e.g. you need to install samsung smart tv sdk. But I'm pretty sure I have just zipped files before.

In your samsung device, in the develop account, you have entered 192.168.1.104 (or whatever your server is running) for application synchronization - right?

regarding size - I don't think that matters much. Perhaps just used for progress bar during download or similar. Or perhaps on some pre-check about available space...

Can you run some network analyzer to see if your device is accessing your server?

**Comment by Tobbe321** [comment]
Well, I just put a html file in the map to see that the webserver responded ok on port 80. And it was displayed OK from another computer.
And the TV also do find the server and tries to install, since it found the name of the app in the widgetlist.xml.

I guess I have to try the SDK then...

**Comment by JeppeTh** [comment]
I meant if  http:/192.168.1.104/widget/"zip-file" was reachable.

**Comment by Tobbe321** [comment]
OK, Yes, the zip.file is reachable from another cumputer via the url in the widgetlist.xml.

I am now downloading the SDK and will test building the package.

**Comment by Pertan** [comment]
Your problem is probably the widget name. You need to rename it to SvtPlay2. ( you need to open the zip archive...)

**Comment by JeppeTh** [comment]
...in the config.xml or whatever it's called...

**Comment by Tobbe321** [comment]
Tried that, expanded the zip, changed the name in config.xml, zipped it and used the same name in widgetlist.xml. No success - same result.
And I realize that i don't know how to use SDK to build a new package, so myabe it's time to give up.
I can run SvtPlay in several other ways.....
But I wonder how you guys made it work?

**Comment by JeppeTh** [comment]
I just followed the guide above (XAMPP and all) and then used this widgetlist:
widgetlist

widgetlist.xml placed in 
C:\Program Files\Xampp\htdocs\

This zip I placed in 
C:\Program Files\Xampp\htdocs\Widget\

Then started apache service in XAMPP and synced my samung device towards 192.168.1.33

**Comment by Tobbe321** [comment]
Success!
My widgetlist and server was exactly like yours also using Xampp, apart from the widget id. 
It seems it has to be "PlaySE" somehow.
Strangely the app in the TV gets the name in config.xml which I had changed to "SvtPlay2"!
Anyway, it works now - many thanks for all tips and help!

**Comment by JeppeTh** [comment]
Strange - can't see anything inside APP is named "PlaySE"... 

EDIT:Except from the zip-file name... Perhaps it must be a prefix to zip-file name?

No issues for you with large categories etc?
I'm working on an optimzed version which seems to work also on my old 2011 bluray at least. Haven't tried on 2010 bluray yet...

**Comment by Pertan** [comment]
So it is working at E & D models, what about 2013-2014, (F & H) ?

**Comment by Tobbe321** [comment]
Hi again,
It is in fact not the widget name after all. I tested with different id names in the widget.xml list and it works, even with different id and prefix in zip file name. 
But not with the zip from github, only with the zip I created myself! 
Very strange as that is created with the same files from the unzipped files from github zip.
Could there be differencies in the PC environment? I have WIn7 64bit.

Anway, so my solution was to
- get the zip from github
- unzip to a new folder
- zip the files in the new folder (i used 7-zip)
- put the new zip in the widget folder on the server
- edit the widget.xml file in the root folder accordingly
- start the webserver (ie xampp)
- sync from TV
- sort the apps in installation date order to update the app list in the TV

Best Regards to you all !

**Comment by Kantaris** [comment]
Hi everyone!
Sorry for really dropping the ball on this project. Was so busy with work and life in general and have a hard time concentrating on multiple things at once. But now that JeppeTh have done a great job with updating the project I would like to get involved again. If all of us where to work together perhaps we could finally get it published on the Samsung app store. What do you guys think?

**Comment by Pertan** [comment]
@Kantaris, that is a great idea, but i assume Samsung might turn us down. The app is currently ok, but SVT keeps changing their web every 6 months or so. JeppeTh changed the links (they are now direct links to SVT instead of towards your server), these links might be obsolete in a few months, no one knows, and Samsung might feel its their responsibility. They dont want ~10k angry users, because that is unfortunately how ppl will feel when it stopps working. Everyone takes this stuff for granted. I believe Samsung could have developed something similar, but they decided not to because of lack of support from SVT. SVT has numerous times said this is not something they support. That is a problem.

The codebase is 95% yours and I am gratefull you did this, whatever reason!

**Comment by JeppeTh** [comment]
Hi.

First of all I uploaded a new version which is optimized to also function on e.g. my 2011 bluray. I hope it doesn't degrade performance on more powerful devices - also that I didn't break anything since I haven't really tested the exactly the same version as in my repo. There's some minor improvements/fixes as well.

Then @Kantaris, not sure what was the major issues for you to get it approved by Samsung the previous attempts? Sure perhaps I can help out a bit if you want - but I really don't know the js language, css and html (apart from what I learnt from google and trial and error) - also my time is very limited ;-)

Then @Pertan has a good point - perhaps this was the reason for @Kantaris to access SVT via a server?

Another option could be to use http://dev.bergqvi.st/we-love-public-service, but it's a bit limited.

**Comment by sventamyra** [comment]
Hi

I'm having similar troubles. I have a webserver with widgetlist.xml on.
I can see the xml file from my web browser:
bild
I downloaded the zip archive and put it in the widget folder. I also tried to unzip and rezip using 7zip on my win7 64bit (and renaming the archive).
The TV seem to find the file, but I get the following message on the TV: "Failed to install. For more information, visit http://www.samsungdforum.com/Support/TVAppsSecurity"

Any ideas? I tried other names in the xml-file
Best regards

**Comment by JeppeTh** [comment]
Is it an f-serie? I recently bought an f-series myself where I got this issue for another app. But playse works for me. 
Perhaps you should try and download Samsung tv sdk and build it with that?

**Comment by sventamyra** [comment]
Its an UE50SE6715. But the old app from kantaris worked. Im newbie. Is there a guide to compiling SDK?

**Comment by JeppeTh** [comment]
Not sure if @Kantaris provided some signature file in his variant, I guess not. 
I guess there're guides if you google. 
But it's pretty simple,  install it.  Unpack the git zip file in a ddirectory within the Apps directory found in the installation directory. 
Then open it from the sdk software and choose package,  the new zip is found in the package directory.

**Comment by sventamyra** [comment]
Ok, tankx. I'll give the zip-file a few more tries first.

**Comment by sventamyra** [comment]
Går samma sak göra med tv4play?

**Comment by JeppeTh** [comment]
Fick du det att funka? Hur?
Ja det hade gått att fixa för tv3, 4, 5, 6, 9 osv också. Troligtvis Inget jag kommer lägga ner tid på dock...

**Comment by sventamyra** [comment]
Nej. Är iväg på kurs. Drömmer lite bara 😄

**Comment by Pertan** [comment]
Såg i din widgetlist att du blandat och gett lite i namngivningen, försök att konsekvent använda samma namn på typ: widgetid, title etc. Jag minns inte vad det stog i JeppeThs kod, men jag såg till att byta namn inne i koden så att den heter PlaySE-loc typ. På det sättet kan du även ha kvar kantaris original app..

**Comment by sventamyra** [comment]
Ok, nu funkar det.
Först så klagar den på - i filnamnet, så jag får döpa om arkivet. Jag har avinstallerat Kantaris App, så nu heter appen PlaySE i widgetlist.xml. Sen gick jag in i config.xml och tog bort mellanslaget i namnet där så det också blev PlaySE, Jag fick det ändå inte att funka, men så insåg jag att jag hade råkat zippa hela mappen, inte bara filerna i den, så när jag zippade bara filerna så funkade det. Någonstans på vägen gjorde jag en f/w uppdatering på TVn också till 002004.
Tack för support. Det är super att ha SVTPlay direkt i TVn!

**Comment by Olofpolof** [comment]
Fick det också att funka genom att packa upp zip-filen och packa om bara själva innehållet. Sen mecka med widgetlist.xml etc men det var zippen som var knepigast. Jag tror det går att länka sin widgetlist direkt till github om du bara ändrar zip-strukturen. Alltså, före:

unzip -l PlaySE-Smart-TV-app-master.zip 
Archive:  PlaySE-Smart-TV-app-master.zip
  Length     Date   Time    Name

---

```
    0  03-11-15 00:41   PlaySE-Smart-TV-app-master/
11203  03-11-15 00:41   PlaySE-Smart-TV-app-master/106.png
10624  03-11-15 00:41   PlaySE-Smart-TV-app-master/115.png
 8569  03-11-15 00:41   PlaySE-Smart-TV-app-master/85.png
 9917  03-11-15 00:41   PlaySE-Smart-TV-app-master/95.png
  402  03-11-15 00:41   PlaySE-Smart-TV-app-master/README.md
 3876  03-11-15 00:41   PlaySE-Smart-TV-app-master/SearchList.html
48128  03-11-15 00:41   PlaySE-Smart-TV-app-master/Thumbs.db
    0  03-11-15 00:41   PlaySE-Smart-TV-app-master/app/
    0  03-11-15 00:41   PlaySE-Smart-TV-app-master/app/javascript/
 3000  03-11-15 00:41   PlaySE-Smart-TV-app-master/app/javascript/Audio.js`
```

 och så vidare

Efter:

unzip -l playsejeppe.zip 
Archive:  playsejeppe.zip

---

```
11203  03-11-15 00:41   106.png
10624  03-11-15 00:41   115.png
 8569  03-11-15 00:41   85.png
 9917  03-11-15 00:41   95.png
  402  03-11-15 00:41   README.md
 3876  03-11-15 00:41   SearchList.html
48128  03-11-15 00:41   Thumbs.db
    0  03-11-15 00:41   app/
 2371  03-11-15 00:41   categories.html
 2456  03-11-15 00:41   categoryDetail.html
 1373  03-11-15 00:41   config.xml`
```

och så vidare.

**Comment by sventamyra** [comment]
Fick ett ryck och började med en TV4 variant. Det var inte så krångligt att parsa ut datat, men jag lyckas inte få videon att spela. I PlaySE skickar man in tex http://www.svtplay.se/video/2731014/melodifestivalen/melodifestivalen-2015-final-melodifestivalen-2015-final som parametern gurl i player.js. Men när jag skickar in motsvarande för TV4, tex http://www.tv4play.se/program/ack-v%C3%A4rmland?video_id=3053513 så stannar den på buffring 0%. Kan det vara så att de har en annan spelare på tv4? Eller har jag kanske missat något grundläggande? Kansle är fel tråd, men det verkade finnas lite kunskap samlat här :)

**Comment by JeppeTh** [comment]
Hmm, tv4 har ett riktigt API - kolla tex i Plex Plugin för hur man navigerar:
https://github.com/plexinc-plugins/TV4-Play.bundle/blob/master/Contents/Code/__init__.py

Sen används kod här för att hämta själva m3u8 filen:
https://github.com/plexinc-plugins/Services.bundle/blob/master/Contents/Service%20Sets/com.plexapp.plugins.tv4play/URL/TV4%20Play/ServiceCode.pys

**Comment by sventamyra** [comment]
Ah, ok tack! Blev lite att skriva om. Kanse borde skaffa Plex istället :)

**Comment by JeppeTh** [comment]
Tja, fördelen med denna är att man inte behöver nån server.

**Comment by sventamyra** [comment]
Provar lite med TV4 i alla fall. i SVTplay så letar man reda på m3u8 sökvägen. För tex Ack Värmland ser det ut såhär på tv4:
0: http://tv4playhds-f.akamaihd.net/z/mp4root/2015-01-29/pid4326265(3053513_,T3MP4130,T3MP43,T3MP48,T3MP415,T3MP425,T3MP435,T3MP445,).mp4.csmil/manifest.f4m
1: http://prima.tv4play.se/multimedia/vman/smiroot/2015-02-19/pid4326265!3053513,T3HSMIL!.smi?
2: http://iosv.tv4play.se/subs/2015-02-20/vid_3053513/prog_index.m3u8?
3: ...

När det är en m3u8-fil så ser det ut som en subtitle. Kan det vara så? Lyckas inte spela den iaf... Jag hade gissat på mp4-filen... Förvirrad

**Comment by JeppeTh** [comment]
Har du kollat 
https://github.com/plexinc-plugins/Services.bundle/blob/master/Contents/Service%20Sets/com.plexapp.plugins.tv4play/URL/TV4%20Play/ServiceCode.pys

Detta är mallen för att slå upp m3u8 om jag minns rätt...
https://prima.tv4play.se/api/web/asset/"ID"/play?protocol=hls&videoFormat=MP4+WEBVTTS

tex
https://prima.tv4play.se/api/web/asset/3053513/play?protocol=hls&videoFormat=MP4+WEBVTTS

Man kan även köra protocol http för att köra mp4 istället för m3u8 - men iaf tidgare har den gått trögt att streama - m3u8 funkar bättre,

WEBVTTS behövs bara för att hämta subtitles - man kan ju sen fixa en m3u8 med subtitles mha PROXY_URL i ovanstående länk.

Kör man bara "....=hls" så får man webvtt subtilefilen som är lättare att parsa.

**Comment by sventamyra** [comment]
Ha! Nu funkar det. Tack! Hade missat slutklämman bara: ?protocol=hls&videoFormat=MP4+WEBVTTS

**Comment by sventamyra** [comment]
Har du liknande API för fler kanaler? Tex Kanal5 eller TV3?

**Comment by JeppeTh** [comment]
Ja, sök efter github plex Viasat respektive kanal5
Eller kolla mina repon...

**Comment by sventamyra** [comment]
Fortsätter att tracka dig i det här spåret :)
Håller på och pusslar med Kanal5. Kikar på det du gjort för Plex. Men där ser jag inte att du plockar ut någon .m3u8-fil. Det verkar vara en HTTPLiveStream-historia. Jag får ut en url som ser ut så här: http://www.kanal5play.se/play/program/227058/video/3518782054
Går den att spela på en Samsung måntro?

**Comment by JeppeTh** [comment]
Nej, det finns m3u8:
https://github.com/JeppeTh/Services.bundle/blob/master/Contents/Service%20Sets/com.plexapp.plugins.kanal5play/URL/Kanal%205%20Play/ServiceCode.pys
Du kan ju kolla api't också:
http://www.kanal5play.se/api

/api/getVideo med tex IPHONE ger m3u8.

**Comment by sventamyra** [comment]
Gott. Tack!

**Comment by JeppeTh** [comment]
If anyone have @Kantaris original 0.3.0 version laying around I would appreciate if I could get hold of it.
Thx.

**Comment by Olofpolof** [comment]
I have a file named "PlaySE_0.030_Europe_20131105.zip". Is it what you're looking for? (how do I send it to you?)

**Comment by JeppeTh** [comment]
@Olofpolof I don't think that's it. That sounds like something you packaged yourself with Samsung TV SDK... But I'm not sure - do you have dropbox or similar?

**Comment by Olofpolof** [comment]
Nope, did not package myself... but downloaded the file about a year ago so dont remember where it's from. Anyhow, download it at https://www.dropbox.com/s/09dehx0khsd7chz/PlaySE_0.030_Europe_20131105.zip?dl=0 and good luck!

**Comment by JeppeTh** [comment]
Ok, thx then @Olofpolof. I'll have a look at it ;)

**Comment by JeppeTh** [comment]
Fixade tillslut de andra kanalerna också @sventamyra, men det hade du ju delvis gort själv också verkar det som...

**Comment by sventamyra** [comment]
Hej. Jag har haft lite dåligt samvete för att jag inte delat med mig. Jag hackade ihop en tv4app och en 5-9-11app. De funkar bra men är inte perfekta. Info-knappen saknas och jag har inte filtrerat bort alla olika varianter av program som inte har några tillgängliga avsnitt. Sen började jag koda en kombinerad med alla kanaler i samma app. Men kom av mig mitt någon gång i våras. Och har inte orkat ta upp det igen. Hur har du gjort?
Viasat gav jag mig aldrig på. Jag fick intryck av att man måste ha ett login för att se ngt. Eller?

**Comment by JeppeTh** [comment]
Jag har nu lagt till viasat (inte viaplay alltså), tv4 o kanal5. Alla i samma app, men inte samtidigt. Man växlar mellan kanalerna med knapp 1,2 resp 3,6,8 resp 4, resp 5,9
För tv4 har jag inte heller filtrerat bort program som endast innehåller drm-skyddat material.

**Comment by sventamyra** [comment]
Kul. Låter som att du kom lite längre än mig. Smart att växla med kanalsiffrorna. Jag började bygga en kanalväljare som förstasida. Men det blev i ärlighetens namn inte så bra. Det var väl därför jag tappade fokus. Jag har nog blandat ihop viasat och viaplay. Klantigt :)

**Comment by JeppeTh** [comment]
Vet inte - en kanalväljare/hjälp-sida eller nåt hade varit mer intuitivt. Men jag kan inte css/html (eller js) särskilt bra så orkade inte krångla med det. Har ofta problem med att det kan se bra ut it emulatorerna - sen så ser det konstigt ut i min 2011 eller 2013 bluray. Massa krångel varje gång.
Så skippade det ;-)

**Comment by sventamyra** [comment]
Mitt projekt havererade, har för mycket på hemmafronten. Så nu använder jag din PlaySE. Funkar fantastiskt bra! Tack för ditt bidrag

Fick dock problem med att köra viasat för ett par uppdateringar sedan. Får inte upp några program längre. Backade till en tidigare och då funkar det. Funkar det på din tv? Kollade koden men genomskådar inte vad som kan vara fel

Tror inte det går skapa issues på din repo, så jag provar här :)

**Comment by JeppeTh** [comment]
Tack för infon - la upp en rättning. Hoppas det ska funka nu.

**Comment by sventamyra** [comment]
Tummen upp!

**Comment by sventamyra** [comment]
Längesedan jag bidrog här, använder dock denna dagligen. Fantastiskt arbete @JeppeTh !
Har sedan en lång tid inte fått upp några bilder i TV4-delen. Blir inte klok på varför.

**Comment by JeppeTh** [comment]
Kul att höra 😊 
Använder den dagligen själv också,  annars hade det inte blivit så mycket gjort med den 😉
Kör du på samma gamla tv? 2012 eller nåt? 
Vet att bilderna (eller tv4 alls) inte funkar i emulator dock.
Skulle kunna vara nåt https relaterat...

**Comment by sventamyra** [comment]
Yes, samma gamla TV, 2012. HAr du uppgraderat? 
Men du ser bilderna iaf förstår jag. Hmm, https, jag har ju 443 i routern mappad mot min NAS.

**Comment by JeppeTh** [comment]
Både ja o nej, har 2013+2015 bluray o skaffade nu en 2016 TV 😉.
Försökte lite igår men kunde inte få bilderna att funka i emulatorn iaf. 
Hittade eventuellt ett fel som kommer nästa gång jag levererar nåt, men tveksam till att det hjälper nåt.

**Comment by sventamyra** [comment]
Ok, tack för att du kollade. Ska kolla om det är porten hos mig

**Comment by sventamyra** [comment]
Har också lite stabilitetsproblem under uppspelning hos mig. 
1. När barnen spolar bakåt på svt, så hänger det sig ofta. Misstänker att det är tvns inbyggda spelare som orsakar det. Har du upplevt det?
2. Ibland kommer uppspelningen inte igång, får spinning wheel oändligt länge. Trycker man stopp och play igen så funkar det

**Comment by JeppeTh** [comment]
1 upplever jag delvis. Bootar tv sen? App hänger åtminstone? 
Bluray är tydligen känsligare än tv, blir varma osv. Åtminstone min ena lider ordentligt av detta. Så tex när man spolar tillbaka på även så hänger det o sen bootar den. 

Svårt att se att detta är nåt jag kan påverka.

2an är inget jag känner igen, men är eventuellt nåt jag skulle kunna påverka. Svårt att säga utan felsöka med loggar osv. Nån särskild kanal eller så?

**Comment by sventamyra** [comment]
1. Yes, tvn bootar om helt. Ja, den är nog tuff att göra ngt med. 
2. SVT skulle jag säga. Men jag ska se om jag kan hitta ett bra exempel som är repeterbart. Återkommer, men kanske dröjer lite

Återigen. Tack för ett fantastiskt arbete 👍

**Comment by sventamyra** [comment]
Hej igen

Tycker det funkar rätt bra nu faktiskt.
Blev lite nyfiken på Plex, så testade det, är dina bundles döda där? SVT/TV4/Viasat osv. Eller funkar de?

**Comment by JeppeTh** [comment]
Mina bundels är döda ja, har inte testat Plex channels på bra länge.
Tröttnade på avsaknad av undertexter o att man var tvungen att ha igång en server.
Så vet inte vad status är för svenska kanaler idag.
Verkar som att plugins inte är öppna längre, hittade iaf inte dem på github längre när jag letade för nåt år sen...

Angående din 2a ovan så gjorde jag en ändring så att det iaf borde skrivas ut nåt fel istället för att bara ladda hela tiden. Men beror lite på vad felet berodde på...

**Pull request closed without merging**
